spring:
  mail:
    host: mail.example.local
    from: no-reply@fitnesstracker.pl
  profiles:
    active: loadInitialData, fake-email
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8069
